### PR TITLE
updated gaussian models 

### PR DESCRIPTION
**Pull request by NicolettaK**
updated `GaussianSynchrotron` and `GaussianDust` modules to speed up the computation for high resolution maps. 
Documentation has also been updated.

### CODE REVIEW

**Comment by zonca** [comment]
Thanks, you probably should also change the maps used for unit test.
You can test locally with:

    python setup.py test -V --pdb

**Comment by NicolettaK** [comment]
Right..
here: 
[Gaussian_synch_23GHz_uRJ_testmap.fits.zip](https://github.com/simonsobs/so_pysm_models/files/2817990/Gaussian_synch_23GHz_uRJ_testmap.fits.zip)
[Gaussian_dust_353GHz_uRJ_testmap.fits.zip](https://github.com/simonsobs/so_pysm_models/files/2817991/Gaussian_dust_353GHz_uRJ_testmap.fits.zip)
same seeds as before

**Comment by zonca** [comment]
thanks, can you please replace the ones in https://github.com/simonsobs/so_pysm_models/tree/master/so_pysm_models/tests/data?

**Comment by NicolettaK** [comment]
Thanks @zonca ! All the issues should be solved now. Test passed.

**Pull request merged**
