### PR TITLE
[WIP] Precomputed alms

### PR DESCRIPTION
**Pull request by zonca**
Reimplementation of https://github.com/simonsobs/mapsims/pull/4 as a PySM component.

@msyriac @ajvanengelen I tried to make this quite generic, I left out the pattern matching for the Alm filename, I think that is specific to SO, it should go into `mapsims`.

So from `mapsims.cmb` we will get configuration parameters for the file we want and then create a `PrecomputedAlms` object.

Then if you send me a sample implementation of the modulation factor, I can implement it in a derivative of this class.

### CODE REVIEW

**Comment by msyriac** [comment]
Hi, does this not support CAR like the original PR? Having CAR support is pretty critical to many LAT pipelines.

**Comment by zonca** [comment]
@msyriac now that the general class structure is defined, can you add CAR support as a Pull Request into the `zonca:precomputed_alms` branch? please also add a test case

**Comment by msyriac** [comment]
@zonca ok, will do

**Comment by zonca** [comment]
@msyriac please make the `pixell` imports optional so that this class can be used without having it installed

**Comment by zonca** [comment]
see @msyriac's pull request into this at https://github.com/zonca/so_pysm_models/pull/1

**Comment by zonca** [comment]
rebased on master and imported test case from `mapsims`

**Pull request merged**
