### PR TITLE
Port code for Gaussian Dust [WIP]

### PR DESCRIPTION
**Pull request by zonca**
First implementation of gaussian dust,
I think there is a bug somewhere, see example usage and comparison with PySM at: https://gist.github.com/zonca/4ddb5e384cb34f8a2945c041d13e9428

See also @NicolettaK 's example at: https://github.com/NicolettaK/BBPipe/blob/mytests/test/inputs/gauss_sims.ipynb

I believe a factor of 0.3 compared to PySM is pretty big, PySM components are also in K_RJ.

@msyriac @NicolettaK can you please crosscheck the code? I'll get back to this myself in the next days.

Another useful thing would be to have a NSIDE 16 map in K_RJ produced by @NicolettaK 's reference code with a fixed seed.

### CODE REVIEW

**Comment by NicolettaK** [comment]
I don't think there is a bug. 
The amplitude of the power spectrum used to generate the gaussian realization of dust is normalized in the SO-SAT region (10% of the sky), using the HFI-353 GHz map. Comparing the amplitude of polarized signal on the whole sky is therefore not correct. 

here a comparison of pysm and gaussian map only o SAT mask.
[https://gist.github.com/NicolettaK/fbe2457fa2591c38fbe9fff0598c51f4](url)
The ~25% difference reflect the signal difference between dust PySM map at 353 GHz and HFI-353, which is something I actually need to check.

**Comment by NicolettaK** [comment]
attached a reference map for unit test. At 353 GHz, nside=16, RJ units.
The map has been generated with `np.random.seed(12)`
[Gaussian_dust_353GHz_uRJ_testmap.fits.zip](https://github.com/simonsobs/so_pysm_models/files/2653235/Gaussian_dust_353GHz_uRJ_testmap.fits.zip)

**Comment by zonca** [comment]
@NicolettaK you are right, the test passes

**Comment by zonca** [comment]
Ok

**Comment by zonca** [comment]
rebased on master

**Comment by zonca** [comment]
thanks @NicolettaK! this is done as well

**Pull request merged**
